import { Event, Seat } from './types';

export const fmt = (n: number) => '$' + n.toLocaleString('es-CL');

export const EVENTS: Event[] = [
  {
    id: '1',
    name: 'Festival Primavera Sound',
    category: 'Festival',
    dates: [
      { id: 'd1', date: 'Sáb 15 Nov', time: '14:00', city: 'Santiago', venue: "Parque O'Higgins" },
      { id: 'd2', date: 'Sáb 22 Nov', time: '14:00', city: 'Concepción', venue: 'Estadio Ester Roa' },
      { id: 'd3', date: 'Sáb 29 Nov', time: '14:00', city: 'La Serena', venue: 'Explanada Municipal' },
    ],
    priceFrom: 45000,
    description: 'El festival de música independiente más grande de Chile. Más de 30 artistas en 4 escenarios durante un día completo de música.',
    mode: 'sector',
    sectors: [
      { id: 's1', name: 'CANCHA GENERAL', price: 45000, avail: 'available' },
      { id: 's2', name: 'PLATEA TECHADA', price: 75000, avail: 'available' },
      { id: 's3', name: 'VIP FRONT', price: 120000, avail: 'few' },
      { id: 's4', name: 'PALCO PREMIUM', price: 200000, avail: 'sold-out' },
    ],
  },
  {
    id: '2',
    name: 'Banda Sonora — Gira Nacional',
    category: 'Música',
    dates: [
      { id: 'd4', date: 'Sáb 8 Nov', time: '21:00', city: 'Santiago', venue: 'Teatro Caupolicán' },
      { id: 'd5', date: 'Lun 10 Nov', time: '21:00', city: 'Viña del Mar', venue: 'Teatro Municipal' },
    ],
    priceFrom: 35000,
    description: 'La gira más esperada del año. Banda Sonora presenta su nuevo álbum en vivo con producción de primer nivel.',
    mode: 'numbered',
    sectors: [
      { id: 'n1', name: 'PLATEA BAJA', price: 65000, avail: 'available', subzones: ['Zona A', 'Zona B', 'Zona C'] },
      { id: 'n2', name: 'PLATEA ALTA', price: 45000, avail: 'available', subzones: ['Zona A', 'Zona B'] },
      { id: 'n3', name: 'CAMPO VIP', price: 85000, avail: 'few', subzones: ['Zona A'] },
    ],
  },
  {
    id: '3',
    name: 'Humor Sin Filtros',
    category: 'Stand Up',
    dates: [
      { id: 'd6', date: 'Vie 31 Oct', time: '20:00', city: 'Santiago', venue: 'Teatro La Cúpula' },
      { id: 'd7', date: 'Sáb 1 Nov', time: '20:00', city: 'Santiago', venue: 'Teatro La Cúpula' },
      { id: 'd8', date: 'Vie 7 Nov', time: '20:00', city: 'Valparaíso', venue: 'Teatro Municipal' },
      { id: 'd9', date: 'Sáb 8 Nov', time: '20:00', city: 'Temuco', venue: 'Teatro Camilo Henríquez' },
    ],
    priceFrom: 15000,
    description: 'Una noche de humor sin filtros con los mejores comediantes emergentes de Chile.',
    mode: 'general',
    generalPrices: [{ name: 'General', price: 15000 }, { name: 'Preferencial', price: 22000 }],
  },
  {
    id: '4',
    name: 'Cumbre Digital 2025',
    category: 'Conferencia',
    dates: [{ id: 'd10', date: 'Mié 12 Nov', time: '09:00', city: 'Santiago', venue: 'Centro de Eventos Parque' }],
    priceFrom: 45000,
    description: 'La conferencia de tecnología e innovación más importante de Chile. Speakers internacionales y talleres prácticos sobre IA y futuro del trabajo.',
    mode: 'nominative',
    generalPrices: [{ name: 'General', price: 45000 }, { name: 'Startup', price: 65000 }, { name: 'Corporativo', price: 120000 }],
    sectors: [
      { id: '4-s1', name: 'General', price: 45000, avail: 'available' },
      { id: '4-s2', name: 'Startup', price: 65000, avail: 'available' },
      { id: '4-s3', name: 'Corporativo', price: 120000, avail: 'available' },
    ],
  },
  {
    id: '5',
    name: 'Electro Night Vol. 8',
    category: 'Electrónica',
    dates: [{ id: 'd11', date: 'Sáb 25 Oct', time: '23:00', city: 'Santiago', venue: 'Club Chocolate' }],
    priceFrom: 12000,
    description: 'La octava edición de la fiesta electrónica más popular de Santiago con DJs internacionales.',
    mode: 'general',
    generalPrices: [{ name: 'Preventa', price: 12000 }, { name: 'Normal', price: 18000 }],
  },
  {
    id: '6',
    name: 'Noche Sinfónica',
    category: 'Clásica',
    dates: [{ id: 'd12', date: 'Jue 6 Nov', time: '20:30', city: 'Santiago', venue: 'Teatro Municipal de Santiago' }],
    priceFrom: 28000,
    description: 'Orquesta Sinfónica Nacional interpreta obras de Beethoven y Mozart en el recinto más emblemático del país.',
    mode: 'numbered',
    sectors: [
      { id: 'nn1', name: 'PLATEA', price: 55000, avail: 'available', subzones: ['Sector A', 'Sector B'] },
      { id: 'nn2', name: 'PALCO BAJO', price: 75000, avail: 'few', subzones: ['Sector A'] },
      { id: 'nn3', name: 'GALERÍA', price: 28000, avail: 'available', subzones: ['Sector A', 'Sector B', 'Sector C'] },
    ],
  },
  {
    id: '7',
    name: 'Rock en el Parque',
    category: 'Música',
    dates: [
      { id: 'd13', date: 'Dom 2 Nov', time: '15:00', city: 'Santiago', venue: 'Parque Bicentenario' },
      { id: 'd14', date: 'Dom 9 Nov', time: '15:00', city: 'Rancagua', venue: 'Estadio El Teniente' },
    ],
    priceFrom: 22000,
    description: 'Un día de rock nacional en vivo con más de 10 bandas emergentes y consagradas.',
    mode: 'general',
    generalPrices: [{ name: 'General', price: 22000 }, { name: 'VIP', price: 40000 }],
  },
  {
    id: '8',
    name: 'Feria del Libro Santiago',
    category: 'Conferencia',
    dates: [
      { id: 'd15', date: 'Jue 6 Nov', time: '10:00', city: 'Santiago', venue: 'Estación Mapocho' },
      { id: 'd16', date: 'Vie 7 Nov', time: '10:00', city: 'Santiago', venue: 'Estación Mapocho' },
      { id: 'd17', date: 'Sáb 8 Nov', time: '10:00', city: 'Santiago', venue: 'Estación Mapocho' },
    ],
    priceFrom: 5000,
    description: 'La feria literaria más importante de Chile con charlas, presentaciones y acceso a cientos de autores.',
    mode: 'general',
    generalPrices: [{ name: 'Entrada diaria', price: 5000 }, { name: 'Pase completo', price: 12000 }],
  },
  {
    id: '9',
    name: 'Tango Porteño en Chile',
    category: 'Teatro',
    dates: [
      { id: 'd18', date: 'Vie 14 Nov', time: '21:00', city: 'Santiago', venue: 'Teatro Oriente' },
      { id: 'd19', date: 'Sáb 15 Nov', time: '21:00', city: 'Viña del Mar', venue: 'Teatro Municipal Viña' },
    ],
    priceFrom: 32000,
    description: 'Espectáculo de tango con bailarines y músicos llegados directamente desde Buenos Aires.',
    mode: 'numbered',
    sectors: [
      { id: 'tng1', name: 'PLATEA', price: 45000, avail: 'available', subzones: ['Sector A', 'Sector B'] },
      { id: 'tng2', name: 'PALCO', price: 65000, avail: 'few', subzones: ['Sector A'] },
      { id: 'tng3', name: 'GALERÍA', price: 32000, avail: 'available', subzones: ['Sector A', 'Sector B'] },
    ],
  },
  {
    id: '10',
    name: 'Ultra Chile 2025',
    category: 'Festival',
    dates: [
      { id: 'd20', date: 'Sáb 6 Dic', time: '16:00', city: 'Santiago', venue: "Parque O'Higgins" },
      { id: 'd21', date: 'Dom 7 Dic', time: '16:00', city: 'Santiago', venue: "Parque O'Higgins" },
    ],
    priceFrom: 89000,
    description: 'El festival de música electrónica más grande del mundo llega a Chile con los mejores DJs internacionales.',
    mode: 'sector',
    sectors: [
      { id: 'u1', name: 'CAMPO GENERAL', price: 89000, avail: 'available' },
      { id: 'u2', name: 'CAMPO VIP', price: 150000, avail: 'few' },
      { id: 'u3', name: 'ULTRA EXPERIENCE', price: 280000, avail: 'few' },
    ],
  },
  {
    id: '11',
    name: 'Comedia en Familia',
    category: 'Teatro',
    dates: [
      { id: 'd22', date: 'Sáb 1 Nov', time: '16:00', city: 'Santiago', venue: 'Teatro San Ginés' },
      { id: 'd23', date: 'Dom 2 Nov', time: '16:00', city: 'Santiago', venue: 'Teatro San Ginés' },
      { id: 'd24', date: 'Sáb 8 Nov', time: '16:00', city: 'Concepción', venue: 'Teatro Bio-Bio' },
    ],
    priceFrom: 8000,
    description: 'Una obra de teatro para toda la familia con mucho humor, música en vivo y sorpresas.',
    mode: 'numbered',
    sectors: [
      { id: 'cf1', name: 'PLATEA', price: 12000, avail: 'available', subzones: ['Sector A', 'Sector B', 'Sector C'] },
      { id: 'cf2', name: 'PALCO', price: 18000, avail: 'available', subzones: ['Sector A'] },
      { id: 'cf3', name: 'GALERÍA', price: 8000, avail: 'available', subzones: ['Sector A', 'Sector B'] },
    ],
  },
  {
    id: '12',
    name: 'DJ Set: Techno Underground',
    category: 'Electrónica',
    dates: [{ id: 'd25', date: 'Vie 21 Nov', time: '23:59', city: 'Valparaíso', venue: 'Club La Matriz' }],
    priceFrom: 9000,
    description: 'Una noche de techno y electrónica underground con los mejores exponentes locales e internacionales.',
    mode: 'general',
    generalPrices: [{ name: 'Preventa', price: 9000 }, { name: 'Puerta', price: 14000 }],
  },
  {
    id: '13',
    name: 'Fútbol: Clásico del Siglo',
    category: 'Deporte',
    dates: [{ id: 'd26', date: 'Dom 16 Nov', time: '18:00', city: 'Santiago', venue: 'Estadio Nacional' }],
    priceFrom: 18000,
    description: 'El partido más esperado del año entre los dos grandes del fútbol chileno. No te lo pierdas.',
    mode: 'sector',
    sectors: [
      { id: 'ft1', name: 'GALERÍA NORTE', price: 18000, avail: 'available' },
      { id: 'ft2', name: 'GALERÍA SUR', price: 18000, avail: 'few' },
      { id: 'ft3', name: 'PLATEA ORIENTE', price: 35000, avail: 'available' },
      { id: 'ft4', name: 'PLATEA PONIENTE', price: 35000, avail: 'available' },
      { id: 'ft5', name: 'PALCO VIP', price: 80000, avail: 'few' },
    ],
  },
  {
    id: '14',
    name: 'Festival de Jazz Providencia',
    category: 'Festival',
    dates: [
      { id: 'd27', date: 'Vie 28 Nov', time: '19:00', city: 'Santiago', venue: 'Plaza Inés de Suárez' },
      { id: 'd28', date: 'Sáb 29 Nov', time: '19:00', city: 'Santiago', venue: 'Plaza Inés de Suárez' },
    ],
    priceFrom: 25000,
    description: 'Dos noches de jazz al aire libre en el corazón de Providencia con artistas nacionales e invitados internacionales.',
    mode: 'general',
    generalPrices: [{ name: 'Noche individual', price: 25000 }, { name: 'Abono 2 noches', price: 40000 }],
  },
  {
    id: '15',
    name: 'Maratón Santiago 2025',
    category: 'Deporte',
    dates: [{ id: 'd29', date: 'Dom 23 Nov', time: '07:30', city: 'Santiago', venue: 'Parque Forestal' }],
    priceFrom: 35000,
    description: 'El evento de running más importante de Chile. Categorías 10K, 21K y 42K disponibles.',
    mode: 'nominative',
    generalPrices: [{ name: '10K', price: 35000 }, { name: '21K', price: 45000 }, { name: '42K', price: 55000 }],
    sectors: [
      { id: '15-s1', name: '10K', price: 35000, avail: 'available' },
      { id: '15-s2', name: '21K', price: 45000, avail: 'available' },
      { id: '15-s3', name: '42K', price: 55000, avail: 'available' },
    ],
  },
  {
    id: '16',
    name: 'Obras de Amor — Teatro',
    category: 'Teatro',
    dates: [
      { id: 'd30', date: 'Jue 20 Nov', time: '20:30', city: 'Santiago', venue: 'Teatro Mori Bellavista' },
      { id: 'd31', date: 'Vie 21 Nov', time: '20:30', city: 'Santiago', venue: 'Teatro Mori Bellavista' },
      { id: 'd32', date: 'Sáb 22 Nov', time: '20:30', city: 'Santiago', venue: 'Teatro Mori Bellavista' },
    ],
    priceFrom: 20000,
    description: 'Una obra de teatro contemporánea sobre las distintas formas del amor en el Chile de hoy.',
    mode: 'numbered',
    sectors: [
      { id: 'oa1', name: 'PLATEA', price: 28000, avail: 'available', subzones: ['Sector A', 'Sector B'] },
      { id: 'oa2', name: 'MEZANINE', price: 20000, avail: 'available', subzones: ['Sector A'] },
    ],
  },
  {
    id: '17',
    name: 'Cumbia All Stars',
    category: 'Música',
    dates: [
      { id: 'd33', date: 'Sáb 29 Nov', time: '21:00', city: 'Santiago', venue: 'Club Espacio Riesco' },
      { id: 'd34', date: 'Dom 30 Nov', time: '20:00', city: 'Antofagasta', venue: 'Enjoy Antofagasta' },
    ],
    priceFrom: 18000,
    description: 'La noche de cumbia más grande del año con las orquestas más populares de Chile y Latinoamérica.',
    mode: 'general',
    generalPrices: [{ name: 'General', price: 18000 }, { name: 'Preferencial', price: 28000 }, { name: 'VIP', price: 50000 }],
  },
  {
    id: '18',
    name: 'Summit Emprendimiento Chile',
    category: 'Conferencia',
    dates: [{ id: 'd35', date: 'Mié 26 Nov', time: '09:00', city: 'Santiago', venue: 'Centro Gabriela Mistral GAM' }],
    priceFrom: 30000,
    description: 'El encuentro de emprendedores más grande de Chile con mentores, inversionistas y casos de éxito reales.',
    mode: 'nominative',
    generalPrices: [{ name: 'Emprendedor', price: 30000 }, { name: 'Empresa', price: 80000 }, { name: 'Estudiante', price: 15000 }],
    sectors: [
      { id: '18-s1', name: 'Emprendedor', price: 30000, avail: 'available' },
      { id: '18-s2', name: 'Empresa', price: 80000, avail: 'available' },
      { id: '18-s3', name: 'Estudiante', price: 15000, avail: 'available' },
    ],
  },
  {
    id: '19',
    name: 'Noche de Brujas — Halloween',
    category: 'Electrónica',
    dates: [{ id: 'd36', date: 'Vie 31 Oct', time: '22:00', city: 'Santiago', venue: 'Blondie Club' }],
    priceFrom: 10000,
    description: 'La fiesta de Halloween más grande de Santiago. Disfraces obligatorios, premiación al mejor disfraz.',
    mode: 'general',
    generalPrices: [{ name: 'Preventa', price: 10000 }, { name: 'Normal', price: 15000 }],
  },
  {
    id: '20',
    name: 'Concierto Sinfónico Navidad',
    category: 'Clásica',
    dates: [
      { id: 'd37', date: 'Sáb 13 Dic', time: '19:00', city: 'Santiago', venue: 'Teatro Municipal de Santiago' },
      { id: 'd38', date: 'Dom 14 Dic', time: '19:00', city: 'Valparaíso', venue: 'Teatro Municipal Valparaíso' },
    ],
    priceFrom: 22000,
    description: 'El concierto navideño más esperado del año con la Orquesta Sinfónica interpretando villancicos y clásicos.',
    mode: 'numbered',
    sectors: [
      { id: 'sn1', name: 'PLATEA', price: 38000, avail: 'available', subzones: ['Sector A', 'Sector B'] },
      { id: 'sn2', name: 'PALCO', price: 55000, avail: 'few', subzones: ['Sector A'] },
      { id: 'sn3', name: 'GALERÍA', price: 22000, avail: 'available', subzones: ['Sector A', 'Sector B', 'Sector C'] },
    ],
  },
  {
    id: '21',
    name: 'Stand Up: Nuevas Voces',
    category: 'Stand Up',
    dates: [
      { id: 'd39', date: 'Jue 13 Nov', time: '21:00', city: 'Santiago', venue: 'Bar El Huaso Enrique' },
      { id: 'd40', date: 'Jue 20 Nov', time: '21:00', city: 'Santiago', venue: 'Bar El Huaso Enrique' },
    ],
    priceFrom: 8000,
    description: 'La vitrina de comedia más importante para nuevos talentos del stand up chileno.',
    mode: 'general',
    generalPrices: [{ name: 'General', price: 8000 }],
  },
  {
    id: '22',
    name: 'Regreso a los 80s',
    category: 'Música',
    dates: [
      { id: 'd41', date: 'Sáb 22 Nov', time: '21:00', city: 'Santiago', venue: 'Movistar Arena' },
    ],
    priceFrom: 38000,
    description: 'La noche retro más grande del año con los mejores éxitos de los años 80 interpretados en vivo.',
    mode: 'sector',
    sectors: [
      { id: 'r1', name: 'CAMPO', price: 38000, avail: 'available' },
      { id: 'r2', name: 'PLATEA', price: 55000, avail: 'available' },
      { id: 'r3', name: 'VIP', price: 90000, avail: 'few' },
    ],
  },
  {
    id: '23',
    name: 'Tenis Abierto Providencia',
    category: 'Deporte',
    dates: [
      { id: 'd42', date: 'Lun 3 Nov', time: '10:00', city: 'Santiago', venue: 'Club de Tenis Providencia' },
      { id: 'd43', date: 'Mar 4 Nov', time: '10:00', city: 'Santiago', venue: 'Club de Tenis Providencia' },
    ],
    priceFrom: 12000,
    description: 'El torneo de tenis más importante de la zona central con jugadores nacionales e internacionales.',
    mode: 'general',
    generalPrices: [{ name: 'Entrada diaria', price: 12000 }, { name: 'Abono semana', price: 20000 }],
  },
  {
    id: '24',
    name: 'Festival Gastronómico Boragó',
    category: 'Festival',
    dates: [
      { id: 'd44', date: 'Sáb 15 Nov', time: '12:00', city: 'Santiago', venue: 'Parque Araucano' },
      { id: 'd45', date: 'Dom 16 Nov', time: '12:00', city: 'Santiago', venue: 'Parque Araucano' },
    ],
    priceFrom: 15000,
    description: 'El encuentro culinario más importante de Chile con chefs de reconocimiento internacional y productos locales.',
    mode: 'general',
    generalPrices: [{ name: 'Entrada diaria', price: 15000 }, { name: 'Abono fin de semana', price: 25000 }],
  },
  {
    id: '25',
    name: 'Ballet: El Lago de los Cisnes',
    category: 'Teatro',
    dates: [
      { id: 'd46', date: 'Vie 5 Dic', time: '20:00', city: 'Santiago', venue: 'Teatro Municipal de Santiago' },
      { id: 'd47', date: 'Sáb 6 Dic', time: '20:00', city: 'Santiago', venue: 'Teatro Municipal de Santiago' },
      { id: 'd48', date: 'Dom 7 Dic', time: '18:00', city: 'Santiago', venue: 'Teatro Municipal de Santiago' },
    ],
    priceFrom: 35000,
    description: 'El ballet clásico más célebre del mundo en una producción de primer nivel con bailarines del Ballet Nacional Chileno.',
    mode: 'numbered',
    sectors: [
      { id: 'bl1', name: 'PLATEA BAJA', price: 65000, avail: 'available', subzones: ['Sector A', 'Sector B', 'Sector C'] },
      { id: 'bl2', name: 'PLATEA ALTA', price: 45000, avail: 'available', subzones: ['Sector A', 'Sector B'] },
      { id: 'bl3', name: 'PALCO', price: 85000, avail: 'few', subzones: ['Sector A'] },
      { id: 'bl4', name: 'GALERÍA', price: 35000, avail: 'available', subzones: ['Sector A', 'Sector B', 'Sector C'] },
    ],
  },
  {
    id: '26',
    name: 'Acid Jazz Night',
    category: 'Electrónica',
    dates: [{ id: 'd49', date: 'Sáb 8 Nov', time: '22:00', city: 'Santiago', venue: 'Club La Batuta' }],
    priceFrom: 11000,
    description: 'Una noche de acid jazz, soul y funk electrónico en el club de música en vivo más emblemático de Ñuñoa.',
    mode: 'general',
    generalPrices: [{ name: 'Preventa', price: 11000 }, { name: 'Puerta', price: 16000 }],
  },
  {
    id: '27',
    name: 'Cumbre Salud Mental 2025',
    category: 'Conferencia',
    dates: [{ id: 'd50', date: 'Vie 28 Nov', time: '09:00', city: 'Santiago', venue: 'Hotel W Santiago' }],
    priceFrom: 55000,
    description: 'Jornada de conversaciones y talleres sobre bienestar mental con psicólogos, psiquiatras y referentes internacionales.',
    mode: 'nominative',
    generalPrices: [{ name: 'Presencial', price: 55000 }, { name: 'Online', price: 25000 }],
    sectors: [
      { id: '27-s1', name: 'Presencial', price: 55000, avail: 'available' },
      { id: '27-s2', name: 'Online', price: 25000, avail: 'available' },
    ],
  },
  {
    id: '28',
    name: 'Los Bunkers — Reencuentro',
    category: 'Música',
    dates: [
      { id: 'd51', date: 'Vie 19 Dic', time: '21:00', city: 'Santiago', venue: 'Movistar Arena' },
      { id: 'd52', date: 'Sáb 20 Dic', time: '21:00', city: 'Concepción', venue: 'Estadio Regional' },
    ],
    priceFrom: 42000,
    description: 'El regreso más esperado del rock nacional. Los Bunkers vuelven a los escenarios después de 10 años.',
    mode: 'sector',
    sectors: [
      { id: 'lb1', name: 'CAMPO', price: 42000, avail: 'available' },
      { id: 'lb2', name: 'PLATEA', price: 65000, avail: 'available' },
      { id: 'lb3', name: 'VIP FRONT', price: 120000, avail: 'few' },
      { id: 'lb4', name: 'PALCO', price: 200000, avail: 'sold-out' },
    ],
  },
  {
    id: '29',
    name: 'Magia en Grande',
    category: 'Teatro',
    dates: [
      { id: 'd53', date: 'Sáb 29 Nov', time: '19:00', city: 'Santiago', venue: 'Teatro Caupolicán' },
      { id: 'd54', date: 'Dom 30 Nov', time: '18:00', city: 'Santiago', venue: 'Teatro Caupolicán' },
    ],
    priceFrom: 18000,
    description: 'El espectáculo de magia e ilusionismo más grande que ha llegado a Chile con artistas de 8 países.',
    mode: 'numbered',
    sectors: [
      { id: 'mg1', name: 'PLATEA', price: 28000, avail: 'available', subzones: ['Sector A', 'Sector B'] },
      { id: 'mg2', name: 'GALERÍA', price: 18000, avail: 'available', subzones: ['Sector A', 'Sector B'] },
    ],
  },
  {
    id: '30',
    name: 'Festival Costumbrista Chiloé',
    category: 'Festival',
    dates: [
      { id: 'd55', date: 'Sáb 6 Dic', time: '11:00', city: 'Castro', venue: 'Plaza de Armas Castro' },
      { id: 'd56', date: 'Dom 7 Dic', time: '11:00', city: 'Castro', venue: 'Plaza de Armas Castro' },
    ],
    priceFrom: 0,
    description: 'La celebración de la cultura y tradiciones de Chiloé con música, gastronomía típica y artesanía local.',
    mode: 'general',
    generalPrices: [{ name: 'Entrada libre', price: 0 }],
  },
];

export const CATEGORIES = ['Todos', 'Festival', 'Música', 'Stand Up', 'Electrónica', 'Conferencia', 'Clásica', 'Teatro'];

export const PAST_TICKETS = [
  {
    id: 'pt1',
    eventName: 'Lollapalooza Chile 2025',
    date: 'Sáb 22 Mar 2025',
    time: '14:00',
    city: 'Santiago',
    venue: "Parque Bicentenario Cerrillos",
    sector: 'Campo General',
    seat: null,
    attendee: null,
    orderId: 'VB-2025-00412',
  },
  {
    id: 'pt2',
    eventName: 'Comedia en Vivo',
    date: 'Vie 5 Feb 2025',
    time: '21:00',
    city: 'Santiago',
    venue: 'Teatro La Cúpula',
    sector: 'General',
    seat: null,
    attendee: null,
    orderId: 'VB-2025-00089',
  },
];

export function generateSeats(subzone: string, price: number): Seat[] {
  const rows = ['A', 'B', 'C', 'D', 'E'];
  const seats: Seat[] = [];
  const occupied = new Set([3, 7, 12, 19, 22, 28, 31, 35, 40, 43]);
  rows.forEach((row, ri) => {
    for (let i = 1; i <= 10; i++) {
      const idx = ri * 10 + i;
      seats.push({
        id: `${subzone}-${row}${i}`,
        row,
        num: i,
        status: occupied.has(idx) ? 'occupied' : 'available',
        price,
      });
    }
  });
  return seats;
}
